defaults: &defaults
  host: 192.168.77.10
  user: vagrant
  adapter: postgresql
  encoding: unicode
  min_messages: WARNING
  pool: 10

development: &development
  <<: *defaults
  database: working_landscapes_development

test: &test
  <<: *defaults
  database: working_landscapes_test
